/**
 * FixingState规则表
 *
 * 数据来源：SharpAstrology.HumanDesign/Utility/HumanDesignUtility.cs Line 94-874
 *
 * 规则表定义：行星 + 闸门 + 爻线 → FixingState
 *
 * FixingState枚举：
 * - None = 0 (无箭头)
 * - Exalted = 1 (▲ 上升/庙旺)
 * - Detriment = 2 (▼ 下降/失势)
 * - Juxtaposed = 3 (✲ 并列 = Exalted | Detriment)
 */

const FixingState = {
  None: 0,
  Exalted: 1,        // ▲
  Detriment: 2,      // ▼
  Juxtaposed: 3      // ✲
};

/**
 * 行星映射
 */
const Planet = {
  Sun: 'Sun',
  Earth: 'Earth',
  Moon: 'Moon',
  NorthNode: 'NorthNode',
  SouthNode: 'SouthNode',
  Mercury: 'Mercury',
  Venus: 'Venus',
  Mars: 'Mars',
  Jupiter: 'Jupiter',
  Saturn: 'Saturn',
  Uranus: 'Uranus',
  Neptune: 'Neptune',
  Pluto: 'Pluto'
};

/**
 * 规则表结构：
 * {
 *   [Planet]: {
 *     [Gate-Line]: FixingState
 *   }
 * }
 *
 * 例如：Moon + Gate37 + Line4 = Exalted
 * fixingRules.Moon['37-4'] = FixingState.Exalted
 */

const fixingRules = {
  Moon: {
    '1-1': FixingState.Exalted,
    '4-1': FixingState.Exalted,
    '4-2': FixingState.Exalted,
    '5-3': FixingState.Detriment,
    '6-5': FixingState.Detriment,
    '7-3': FixingState.Exalted,
    '8-3': FixingState.Exalted,
    '9-4': FixingState.Exalted,
    '9-6': FixingState.Exalted,
    '10-1': FixingState.Detriment,
    '10-3': FixingState.Detriment,
    '11-1': FixingState.Exalted,
    '11-4': FixingState.Exalted,
    '11-5': FixingState.Exalted,
    '13-1': FixingState.Detriment,
    '13-2': FixingState.Exalted,
    '14-4': FixingState.Exalted,
    '16-3': FixingState.Exalted,
    '16-5': FixingState.Detriment,
    '17-2': FixingState.Detriment,
    '17-6': FixingState.Exalted,
    '18-2': FixingState.Detriment,
    '18-6': FixingState.Detriment,
    '19-1': FixingState.Detriment,
    '19-3': FixingState.Detriment,
    '20-1': FixingState.Detriment,
    '20-2': FixingState.Detriment,
    '21-1': FixingState.Detriment,
    '22-1': FixingState.Exalted,
    '23-2': FixingState.Detriment,
    '23-5': FixingState.Detriment,
    '24-2': FixingState.Exalted,
    '24-5': FixingState.Exalted,
    '26-6': FixingState.Detriment,
    '27-2': FixingState.Exalted,
    '27-6': FixingState.Exalted,
    '30-6': FixingState.Detriment,
    '31-4': FixingState.Exalted,
    '31-5': FixingState.Detriment,
    '31-6': FixingState.Detriment,
    '32-5': FixingState.Exalted,
    '34-5': FixingState.Detriment,
    '35-2': FixingState.Detriment,
    '35-4': FixingState.Exalted,
    '36-2': FixingState.Detriment,
    '36-4': FixingState.Detriment,
    '37-4': FixingState.Exalted,  // ← 关键！Neptune 37.4通过这条规则获得▲
    '38-2': FixingState.Detriment,
    '39-2': FixingState.Exalted,
    '39-4': FixingState.Exalted,
    '39-6': FixingState.Exalted,
    '40-1': FixingState.Detriment,
    '40-2': FixingState.Detriment,
    '41-3': FixingState.Detriment,
    '42-3': FixingState.Detriment,
    '42-4': FixingState.Exalted,
    '42-6': FixingState.Exalted,
    '43-2': FixingState.Detriment,
    '43-3': FixingState.Detriment,
    '43-5': FixingState.Exalted,
    '46-3': FixingState.Exalted,
    '46-5': FixingState.Exalted,
    '47-4': FixingState.Detriment,
    '48-1': FixingState.Exalted,  // ← 关键！月亮48.1是▲
    '48-3': FixingState.Exalted,
    '48-5': FixingState.Detriment,
    '48-6': FixingState.Detriment,
    '49-5': FixingState.Exalted,
    '50-3': FixingState.Exalted,
    '50-6': FixingState.Detriment,
    '53-2': FixingState.Exalted,
    '53-3': FixingState.Exalted,
    '53-4': FixingState.Exalted,
    '53-6': FixingState.Exalted,
    '55-6': FixingState.Detriment,
    '56-1': FixingState.Exalted,
    '56-2': FixingState.Detriment,
    '56-4': FixingState.Exalted,
    '57-1': FixingState.Detriment,
    '57-2': FixingState.Detriment,
    '57-5': FixingState.Detriment,
    '58-1': FixingState.Detriment,
    '58-5': FixingState.Exalted,
    '58-6': FixingState.Exalted,
    '61-2': FixingState.Exalted,
    '61-3': FixingState.Exalted,
    '62-5': FixingState.Exalted,
    '64-2': FixingState.Detriment,
    '64-3': FixingState.Detriment,
    '64-4': FixingState.Exalted
  },

  Earth: {
    '1-3': FixingState.Detriment,
    '1-4': FixingState.Exalted,
    '1-6': FixingState.Exalted,
    '2-5': FixingState.Detriment,
    '3-1': FixingState.Exalted,
    '3-5': FixingState.Detriment,
    '4-1': FixingState.Detriment,
    '5-1': FixingState.Detriment,
    '8-2': FixingState.Detriment,
    '9-3': FixingState.Exalted,
    '9-5': FixingState.Detriment,
    '10-3': FixingState.Exalted,
    '12-4': FixingState.Exalted,
    '12-6': FixingState.Detriment,
    '13-3': FixingState.Exalted,
    '14-3': FixingState.Exalted,
    '14-6': FixingState.Detriment,
    '15-2': FixingState.Detriment,
    '15-3': FixingState.Exalted,
    '16-1': FixingState.Exalted,
    '17-3': FixingState.Detriment,
    '18-1': FixingState.Exalted,
    '18-4': FixingState.Exalted,
    '19-5': FixingState.Exalted,
    '20-3': FixingState.Detriment,
    '21-4': FixingState.Detriment,
    '23-4': FixingState.Detriment,
    '25-6': FixingState.Exalted,
    '27-1': FixingState.Detriment,  // ← 2017案例：红地球27.1是▼
    '29-5': FixingState.Detriment,
    '31-1': FixingState.Detriment,
    '34-6': FixingState.Exalted,
    '38-3': FixingState.Detriment,
    '38-6': FixingState.Detriment,
    '39-3': FixingState.Detriment,
    '40-5': FixingState.Detriment,
    '40-6': FixingState.Detriment,
    '41-4': FixingState.Exalted,
    '44-6': FixingState.Detriment,
    '46-4': FixingState.Exalted,
    '48-4': FixingState.Detriment,
    '49-2': FixingState.Exalted,
    '52-1': FixingState.Exalted,
    '52-5': FixingState.Exalted,
    '53-5': FixingState.Detriment,
    '55-2': FixingState.Detriment,
    '60-2': FixingState.Detriment
  },

  // 由于规则表非常大，我先实现关键行星的规则
  // 继续添加其他行星...

  Pluto: {
    '1-6': FixingState.Detriment,
    '3-3': FixingState.Detriment,
    '3-6': FixingState.Detriment,
    '4-3': FixingState.Detriment,
    '4-5': FixingState.Detriment,
    '5-2': FixingState.Detriment,
    '5-5': FixingState.Detriment,
    '6-1': FixingState.Exalted,
    '6-3': FixingState.Detriment,
    '6-4': FixingState.Detriment,
    '8-6': FixingState.Detriment,
    '9-1': FixingState.Exalted,
    '9-2': FixingState.Exalted,
    '9-6': FixingState.Detriment,
    '10-6': FixingState.Exalted,
    '11-3': FixingState.Exalted,
    '13-4': FixingState.Exalted,
    '15-5': FixingState.Detriment,
    '15-6': FixingState.Exalted,
    '16-5': FixingState.Exalted,
    '17-3': FixingState.Exalted,
    '17-4': FixingState.Exalted,
    '18-2': FixingState.Exalted,
    '21-5': FixingState.Detriment,
    '21-6': FixingState.Exalted,
    '23-3': FixingState.Detriment,
    '24-6': FixingState.Detriment,
    '25-3': FixingState.Detriment,
    '26-2': FixingState.Detriment,
    '26-4': FixingState.Exalted,
    '27-3': FixingState.Exalted,
    '27-6': FixingState.Detriment,
    '28-5': FixingState.Exalted,
    '28-6': FixingState.Exalted,
    '30-3': FixingState.Exalted,
    '30-4': FixingState.Exalted,
    '30-5': FixingState.Detriment,
    '31-5': FixingState.Exalted,
    '32-6': FixingState.Exalted,
    '33-4': FixingState.Exalted,
    '33-5': FixingState.Exalted,
    '34-1': FixingState.Detriment,
    '34-4': FixingState.Exalted,
    '36-3': FixingState.Exalted,
    '36-4': FixingState.Exalted,
    '36-5': FixingState.Exalted,
    '38-2': FixingState.Exalted,
    '38-4': FixingState.Exalted,
    '38-5': FixingState.Detriment,
    '40-3': FixingState.Exalted,
    '41-6': FixingState.Detriment,
    '43-1': FixingState.Exalted,
    '43-2': FixingState.Exalted,
    '43-3': FixingState.Exalted,
    '44-1': FixingState.Exalted,
    '44-4': FixingState.Exalted,
    '44-6': FixingState.Exalted,
    '46-4': FixingState.Detriment,
    '48-2': FixingState.Exalted,
    '49-2': FixingState.Detriment,
    '49-3': FixingState.Detriment,
    '51-1': FixingState.Exalted,
    '51-6': FixingState.Detriment,
    '52-5': FixingState.Detriment,
    '53-6': FixingState.Detriment,
    '54-1': FixingState.Exalted,  // ← 2017案例：红冥王星54.1是▲
    '54-3': FixingState.Exalted,  // ← 2017案例：黑冥王星54.3是▲
    '56-6': FixingState.Detriment,
    '57-5': FixingState.Exalted,
    '58-4': FixingState.Exalted,
    '59-2': FixingState.Detriment,
    '61-6': FixingState.Exalted,
    '62-4': FixingState.Detriment,
    '63-6': FixingState.Detriment
  },

  Jupiter: {
    '1-4': FixingState.Detriment,
    '2-3': FixingState.Exalted,
    '4-5': FixingState.Exalted,
    '8-4': FixingState.Exalted,
    '8-5': FixingState.Exalted,
    '9-2': FixingState.Detriment,
    '9-5': FixingState.Exalted,
    '10-5': FixingState.Exalted,
    '11-6': FixingState.Detriment,
    '12-1': FixingState.Detriment,
    '13-5': FixingState.Detriment,
    '14-1': FixingState.Exalted,
    '14-2': FixingState.Exalted,
    '15-4': FixingState.Exalted,
    '15-5': FixingState.Exalted,
    '16-4': FixingState.Exalted,
    '16-6': FixingState.Detriment,
    '17-4': FixingState.Detriment,
    '17-6': FixingState.Detriment,
    '18-1': FixingState.Detriment,
    '18-3': FixingState.Detriment,
    '19-2': FixingState.Exalted,
    '19-5': FixingState.Detriment,
    '19-6': FixingState.Exalted,
    '20-4': FixingState.Exalted,
    '21-3': FixingState.Detriment,
    '21-4': FixingState.Exalted,
    '21-5': FixingState.Exalted,
    '22-2': FixingState.Detriment,
    '22-5': FixingState.Exalted,
    '23-1': FixingState.Exalted,
    '23-2': FixingState.Exalted,
    '23-5': FixingState.Exalted,
    '23-6': FixingState.Detriment,
    '24-3': FixingState.Detriment,
    '24-6': FixingState.Exalted,
    '25-4': FixingState.Exalted,
    '25-5': FixingState.Detriment,
    '27-4': FixingState.Exalted,
    '27-5': FixingState.Exalted,
    '28-2': FixingState.Detriment,
    '28-3': FixingState.Detriment,
    '28-4': FixingState.Exalted,
    '29-3': FixingState.Detriment,
    '29-6': FixingState.Detriment,
    '30-1': FixingState.Detriment,
    '30-3': FixingState.Detriment,
    '30-4': FixingState.Detriment,
    '30-5': FixingState.Exalted,
    '31-2': FixingState.Exalted,
    '31-3': FixingState.Detriment,
    '32-2': FixingState.Detriment,
    '32-3': FixingState.Detriment,  // ← 2017案例：黑木星32.3是▼
    '32-4': FixingState.Exalted,
    '33-2': FixingState.Exalted,
    '33-3': FixingState.Exalted,
    '33-5': FixingState.Detriment,
    '33-6': FixingState.Detriment,
    '34-6': FixingState.Detriment,
    '35-3': FixingState.Exalted,
    '35-5': FixingState.Detriment,
    '36-1': FixingState.Detriment,
    '36-3': FixingState.Detriment,
    '36-6': FixingState.Exalted,
    '37-2': FixingState.Exalted,
    '37-3': FixingState.Exalted,
    '39-2': FixingState.Detriment,
    '39-3': FixingState.Exalted,
    '43-4': FixingState.Detriment,
    '44-2': FixingState.Exalted,
    '45-1': FixingState.Exalted,  // ← 注意：这是Jupiter的规则！
    '45-4': FixingState.Exalted,
    '45-5': FixingState.Detriment,
    '45-6': FixingState.Detriment,
    '46-1': FixingState.Detriment,
    '47-3': FixingState.Exalted,
    '49-1': FixingState.Exalted,
    '49-4': FixingState.Exalted,
    '51-3': FixingState.Detriment,
    '52-4': FixingState.Detriment,
    '54-6': FixingState.Detriment,
    '55-1': FixingState.Exalted,
    '55-4': FixingState.Exalted,
    '60-5': FixingState.Detriment,
    '61-4': FixingState.Detriment,
    '63-2': FixingState.Exalted,
    '63-3': FixingState.Exalted,
    '63-6': FixingState.Exalted,
    '64-5': FixingState.Detriment
  },

  Sun: {
    '3-6': FixingState.Exalted,
    '4-4': FixingState.Exalted,
    '5-4': FixingState.Detriment,
    '6-4': FixingState.Exalted,
    '7-4': FixingState.Exalted,
    '8-2': FixingState.Exalted,
    '8-5': FixingState.Detriment,
    '9-3': FixingState.Detriment,
    '10-1': FixingState.Exalted,
    '11-4': FixingState.Detriment,
    '12-5': FixingState.Exalted,
    '12-6': FixingState.Exalted,
    '13-2': FixingState.Detriment,
    '14-5': FixingState.Exalted,
    '14-6': FixingState.Exalted,
    '15-2': FixingState.Exalted,
    '16-2': FixingState.Exalted,
    '17-2': FixingState.Exalted,
    '19-1': FixingState.Exalted,
    '20-3': FixingState.Exalted,
    '22-2': FixingState.Exalted,
    '22-6': FixingState.Exalted,
    '23-3': FixingState.Exalted,
    '23-4': FixingState.Exalted,
    '24-1': FixingState.Exalted,
    '26-2': FixingState.Exalted,
    '26-3': FixingState.Exalted,
    '26-6': FixingState.Exalted,
    '27-1': FixingState.Exalted,
    '28-2': FixingState.Exalted,
    '28-5': FixingState.Detriment,
    '29-2': FixingState.Exalted,
    '29-5': FixingState.Exalted,
    '30-1': FixingState.Exalted,
    '30-2': FixingState.Exalted,
    '31-1': FixingState.Exalted,
    '31-3': FixingState.Exalted,
    '31-6': FixingState.Exalted,
    '32-1': FixingState.Exalted,  // ← 1983案例：黑太阳32.1是▲
    '33-1': FixingState.Exalted,
    '33-6': FixingState.Exalted,
    '35-3': FixingState.Detriment,
    '38-3': FixingState.Exalted,
    '39-4': FixingState.Detriment,
    '40-1': FixingState.Exalted,
    '40-2': FixingState.Exalted,
    '40-6': FixingState.Exalted,
    '42-1': FixingState.Exalted,
    '42-2': FixingState.Exalted,
    '42-5': FixingState.Exalted,
    '43-6': FixingState.Exalted,
    '44-4': FixingState.Detriment,
    '46-2': FixingState.Exalted,
    '47-6': FixingState.Detriment,
    '48-4': FixingState.Exalted,
    '49-1': FixingState.Detriment,
    '50-2': FixingState.Exalted,
    '51-3': FixingState.Exalted,
    '51-5': FixingState.Exalted,
    '51-6': FixingState.Exalted,
    '54-5': FixingState.Exalted,
    '55-5': FixingState.Detriment,
    '56-3': FixingState.Exalted,
    '56-6': FixingState.Exalted,
    '58-5': FixingState.Detriment,
    '59-1': FixingState.Exalted,
    '59-5': FixingState.Exalted,
    '63-1': FixingState.Exalted,
    '63-5': FixingState.Exalted
  },

  Mercury: {
    '2-5': FixingState.Exalted,
    '2-6': FixingState.Exalted,
    '3-1': FixingState.Detriment,
    '4-6': FixingState.Exalted,
    '6-1': FixingState.Detriment,
    '6-6': FixingState.Exalted,
    '7-1': FixingState.Detriment,
    '7-2': FixingState.Detriment,
    '7-3': FixingState.Detriment,
    '7-6': FixingState.Exalted,
    '8-1': FixingState.Detriment,
    '8-4': FixingState.Detriment,
    '10-2': FixingState.Exalted,
    '10-4': FixingState.Detriment,
    '11-5': FixingState.Detriment,
    '12-2': FixingState.Detriment,
    '12-4': FixingState.Detriment,
    '13-6': FixingState.Detriment,
    '14-1': FixingState.Detriment,
    '15-3': FixingState.Detriment,
    '16-1': FixingState.Detriment,
    '16-2': FixingState.Detriment,
    '18-4': FixingState.Detriment,
    '19-2': FixingState.Detriment,
    '20-4': FixingState.Detriment,
    '20-6': FixingState.Detriment,
    '25-1': FixingState.Detriment,
    '25-2': FixingState.Exalted,
    '28-4': FixingState.Detriment,
    '31-2': FixingState.Detriment,
    '32-3': FixingState.Exalted,
    '34-3': FixingState.Detriment,
    '35-5': FixingState.Exalted,
    '36-5': FixingState.Detriment,
    '37-2': FixingState.Detriment,
    '37-6': FixingState.Detriment,
    '39-1': FixingState.Detriment,
    '41-1': FixingState.Detriment,
    '43-4': FixingState.Exalted,
    '47-2': FixingState.Detriment,
    '48-3': FixingState.Detriment,  // 水星48.3是▼，但48.1无规则
    '50-3': FixingState.Detriment,
    '51-2': FixingState.Detriment,
    '51-4': FixingState.Detriment,
    '56-4': FixingState.Detriment,
    '57-3': FixingState.Exalted,
    '58-6': FixingState.Detriment,
    '59-1': FixingState.Detriment,
    '59-4': FixingState.Detriment,
    '59-6': FixingState.Detriment,
    '60-1': FixingState.Detriment,
    '60-4': FixingState.Exalted,
    '60-6': FixingState.Detriment,
    '62-2': FixingState.Detriment,
    '62-6': FixingState.Detriment,
    '63-4': FixingState.Exalted,
    '64-6': FixingState.Exalted
  },

  Neptune: {
    '3-4': FixingState.Exalted,
    '5-3': FixingState.Exalted,
    '5-6': FixingState.Exalted,
    '6-3': FixingState.Exalted,
    '7-2': FixingState.Exalted,
    '7-5': FixingState.Detriment,
    '8-1': FixingState.Exalted,
    '11-2': FixingState.Exalted,
    '11-6': FixingState.Exalted,
    '12-3': FixingState.Exalted,
    '13-5': FixingState.Exalted,
    '14-3': FixingState.Detriment,
    '16-6': FixingState.Exalted,
    '18-3': FixingState.Exalted,
    '21-2': FixingState.Detriment,
    '21-3': FixingState.Exalted,
    '22-4': FixingState.Exalted,
    '24-1': FixingState.Detriment,
    '24-4': FixingState.Detriment,
    '25-1': FixingState.Exalted,
    '26-1': FixingState.Exalted,
    '28-6': FixingState.Detriment,
    '29-1': FixingState.Detriment,
    '32-6': FixingState.Detriment,
    '33-2': FixingState.Detriment,
    '33-4': FixingState.Detriment,
    '35-1': FixingState.Detriment,
    '36-2': FixingState.Exalted,
    '38-1': FixingState.Exalted,
    '39-5': FixingState.Exalted,
    '41-1': FixingState.Exalted,
    '44-3': FixingState.Detriment,
    '45-3': FixingState.Exalted,
    '46-1': FixingState.Exalted,
    '46-5': FixingState.Detriment,
    '46-6': FixingState.Detriment,
    '47-1': FixingState.Detriment,
    '49-3': FixingState.Exalted,
    '49-6': FixingState.Exalted,
    '52-6': FixingState.Detriment,
    '53-1': FixingState.Exalted,
    '53-5': FixingState.Exalted,
    '58-4': FixingState.Detriment,
    '60-5': FixingState.Exalted,
    '61-1': FixingState.Exalted,
    '62-1': FixingState.Exalted,
    '62-5': FixingState.Detriment
  }

  // 注意：北交点和南交点没有直接的规则表
  // 它们可能通过其他行星的聚合获得箭头
};

/**
 * 查询FixingState规则
 * @param {string} planet - 行星名称
 * @param {number} gate - 闸门 (1-64)
 * @param {number} line - 爻线 (1-6)
 * @returns {number} FixingState值
 */
function getFixingState(planet, gate, line) {
  const planetRules = fixingRules[planet];
  if (!planetRules) {
    return FixingState.None;
  }

  const key = `${gate}-${line}`;
  return planetRules[key] || FixingState.None;
}

module.exports = {
  FixingState,
  Planet,
  fixingRules,
  getFixingState
};
